from dataclasses import dataclass
from typing import List

@dataclass
class CareerPath:
    name: str
    category: str
    description: str
    required_skills: List[str]
    typical_roles: List[str]

CAREER_PATHS = {
    "STEM": [
        CareerPath("Software Engineering", "STEM", "Design and develop software applications and systems", 
                  ["Programming", "Problem-solving", "Logic"], ["Developer", "Engineer", "Architect"]),
        CareerPath("Data Science", "STEM", "Analyze data to extract insights and build predictive models",
                  ["Statistics", "Programming", "Analytics"], ["Data Scientist", "Analyst", "ML Engineer"]),
        CareerPath("Biomedical Research", "STEM", "Conduct research to advance medical knowledge and treatments",
                  ["Research", "Biology", "Critical thinking"], ["Researcher", "Lab Technician", "Scientist"]),
        CareerPath("Engineering", "STEM", "Design and build solutions to technical problems",
                  ["Math", "Physics", "Design"], ["Civil Engineer", "Mechanical Engineer", "Electrical Engineer"]),
        CareerPath("Cybersecurity", "STEM", "Protect digital systems and data from security threats",
                  ["Network security", "Risk assessment", "Problem-solving"], ["Security Analyst", "Penetration Tester", "CISO"]),
        CareerPath("Artificial Intelligence", "STEM", "Develop AI systems and machine learning models",
                  ["Machine learning", "Programming", "Mathematics"], ["AI Engineer", "ML Researcher", "AI Product Manager"]),
        CareerPath("Robotics", "STEM", "Design and build robotic systems for various applications",
                  ["Mechanical engineering", "Programming", "Electronics"], ["Robotics Engineer", "Automation Specialist", "R&D Engineer"]),
        CareerPath("Biotechnology", "STEM", "Apply biological processes to develop products and technologies",
                  ["Biology", "Chemistry", "Research"], ["Biotech Researcher", "Lab Manager", "Product Developer"]),
        CareerPath("Environmental Science", "STEM", "Study and solve environmental problems",
                  ["Environmental science", "Research", "Data analysis"], ["Environmental Consultant", "Sustainability Manager", "Research Scientist"]),
        CareerPath("Mathematics", "STEM", "Apply mathematical principles to solve real-world problems",
                  ["Advanced math", "Logic", "Analysis"], ["Mathematician", "Statistician", "Quantitative Analyst"]),
        CareerPath("Physics", "STEM", "Study matter, energy, and their interactions",
                  ["Physics", "Mathematics", "Research"], ["Physicist", "Research Scientist", "Lab Director"]),
        CareerPath("Chemistry", "STEM", "Study chemical properties and reactions",
                  ["Chemistry", "Lab skills", "Analysis"], ["Chemist", "Lab Technician", "Quality Control Specialist"]),
        CareerPath("Aerospace Engineering", "STEM", "Design aircraft, spacecraft, and related systems",
                  ["Engineering", "Physics", "CAD design"], ["Aerospace Engineer", "Flight Test Engineer", "Systems Engineer"]),
        CareerPath("UX/UI Design", "STEM", "Design user interfaces and experiences for digital products",
                  ["Design thinking", "User research", "Prototyping"], ["UX Designer", "UI Designer", "Product Designer"]),
        CareerPath("Game Development", "STEM", "Create video games and interactive entertainment",
                  ["Programming", "Game design", "Graphics"], ["Game Developer", "Game Designer", "Technical Artist"])
    ],
    "Arts": [
        CareerPath("Graphic Design", "Arts", "Create visual content for digital and print media",
                  ["Creativity", "Design software", "Visual communication"], ["Designer", "Art Director", "Creative Lead"]),
        CareerPath("Music Production", "Arts", "Create, record, and produce musical content",
                  ["Music theory", "Audio editing", "Creativity"], ["Producer", "Sound Engineer", "Composer"]),
        CareerPath("Writing & Journalism", "Arts", "Create written content for various media and audiences",
                  ["Writing", "Research", "Communication"], ["Writer", "Journalist", "Editor", "Content Creator"]),
        CareerPath("Film & Video", "Arts", "Create visual storytelling content for entertainment and media",
                  ["Storytelling", "Video editing", "Creativity"], ["Director", "Editor", "Cinematographer"]),
        CareerPath("Photography", "Arts", "Capture and edit images for artistic or commercial purposes",
                  ["Photography", "Photo editing", "Visual storytelling"], ["Photographer", "Photo Editor", "Visual Artist"]),
        CareerPath("Fashion Design", "Arts", "Design clothing and accessories",
                  ["Design", "Textile knowledge", "Trend analysis"], ["Fashion Designer", "Stylist", "Creative Director"]),
        CareerPath("Interior Design", "Arts", "Design interior spaces for functionality and aesthetics",
                  ["Space planning", "Color theory", "CAD software"], ["Interior Designer", "Space Planner", "Design Consultant"]),
        CareerPath("Animation", "Arts", "Create animated content for film, TV, games, and digital media",
                  ["Animation software", "Storytelling", "Drawing"], ["Animator", "Motion Graphics Designer", "3D Artist"]),
        CareerPath("Theater Arts", "Arts", "Perform in or produce theatrical productions",
                  ["Acting", "Stage presence", "Collaboration"], ["Actor", "Director", "Stage Manager"]),
        CareerPath("Fine Arts", "Arts", "Create original artwork for galleries and collectors",
                  ["Artistic skills", "Creativity", "Art history"], ["Artist", "Gallery Curator", "Art Teacher"]),
        CareerPath("Digital Art", "Arts", "Create digital artwork and illustrations",
                  ["Digital tools", "Illustration", "Creativity"], ["Digital Artist", "Concept Artist", "Illustrator"]),
        CareerPath("Architecture", "Arts", "Design buildings and structures",
                  ["Design", "CAD software", "Building codes"], ["Architect", "Urban Planner", "Design Consultant"])
    ],
    "Sports": [
        CareerPath("Athletic Training", "Sports", "Help athletes prevent and recover from injuries",
                  ["Anatomy", "Physical therapy", "Sports knowledge"], ["Trainer", "Therapist", "Coach"]),
        CareerPath("Sports Management", "Sports", "Manage sports teams, facilities, and events",
                  ["Management", "Business", "Sports knowledge"], ["Manager", "Agent", "Event Coordinator"]),
        CareerPath("Fitness Coaching", "Sports", "Help individuals achieve their fitness and health goals",
                  ["Exercise science", "Motivation", "Communication"], ["Personal Trainer", "Coach", "Instructor"]),
        CareerPath("Sports Broadcasting", "Sports", "Cover sports events through media and commentary",
                  ["Communication", "Sports knowledge", "Media skills"], ["Sports Commentator", "Sports Journalist", "Broadcaster"]),
        CareerPath("Sports Psychology", "Sports", "Help athletes with mental performance and well-being",
                  ["Psychology", "Sports knowledge", "Counseling"], ["Sports Psychologist", "Mental Performance Coach", "Counselor"]),
        CareerPath("Recreation Management", "Sports", "Manage recreational facilities and programs",
                  ["Management", "Program planning", "Customer service"], ["Recreation Director", "Program Coordinator", "Facility Manager"]),
        CareerPath("Sports Medicine", "Sports", "Provide medical care for athletes and active individuals",
                  ["Medical knowledge", "Sports science", "Rehabilitation"], ["Sports Medicine Doctor", "Physical Therapist", "Orthopedic Specialist"]),
        CareerPath("Professional Athletics", "Sports", "Compete at the highest levels in various sports",
                  ["Athletic ability", "Dedication", "Mental toughness"], ["Professional Athlete", "Team Captain", "Sports Ambassador"])
    ],
    "Business": [
        CareerPath("Marketing", "Business", "Promote products and services to target audiences",
                  ["Communication", "Analytics", "Creativity"], ["Marketer", "Brand Manager", "Social Media Manager"]),
        CareerPath("Finance", "Business", "Manage money, investments, and financial planning",
                  ["Math", "Analytics", "Risk assessment"], ["Analyst", "Advisor", "Investment Banker"]),
        CareerPath("Entrepreneurship", "Business", "Start and run your own business ventures",
                  ["Leadership", "Risk-taking", "Innovation"], ["Founder", "CEO", "Business Owner"]),
        CareerPath("Human Resources", "Business", "Manage employee relations and organizational development",
                  ["Communication", "Psychology", "Policy knowledge"], ["HR Manager", "Recruiter", "Training Coordinator"]),
        CareerPath("Project Management", "Business", "Lead and coordinate projects to successful completion",
                  ["Organization", "Leadership", "Communication"], ["Project Manager", "Program Manager", "Scrum Master"]),
        CareerPath("Sales", "Business", "Sell products and services to customers and clients",
                  ["Communication", "Persuasion", "Relationship building"], ["Sales Representative", "Account Manager", "Sales Director"]),
        CareerPath("Consulting", "Business", "Provide expert advice to organizations",
                  ["Problem-solving", "Analysis", "Communication"], ["Management Consultant", "Strategy Consultant", "Specialist Advisor"]),
        CareerPath("Operations Management", "Business", "Oversee daily business operations and processes",
                  ["Process improvement", "Leadership", "Analytics"], ["Operations Manager", "Process Manager", "COO"]),
        CareerPath("Supply Chain Management", "Business", "Manage the flow of goods and services",
                  ["Logistics", "Analytics", "Coordination"], ["Supply Chain Manager", "Logistics Coordinator", "Procurement Specialist"]),
        CareerPath("Business Analytics", "Business", "Analyze business data to inform decision-making",
                  ["Data analysis", "Statistics", "Business acumen"], ["Business Analyst", "Data Analyst", "Insights Manager"]),
        CareerPath("Real Estate", "Business", "Buy, sell, and manage property transactions",
                  ["Negotiation", "Market knowledge", "Communication"], ["Real Estate Agent", "Property Manager", "Real Estate Developer"]),
        CareerPath("Insurance", "Business", "Assess and manage risk through insurance products",
                  ["Risk assessment", "Mathematics", "Customer service"], ["Insurance Agent", "Underwriter", "Claims Adjuster"])
    ],
    "Healthcare": [
        CareerPath("Nursing", "Healthcare", "Provide direct patient care and medical support",
                  ["Empathy", "Medical knowledge", "Communication"], ["Nurse", "Nurse Practitioner", "Care Manager"]),
        CareerPath("Psychology", "Healthcare", "Help people with mental health and behavioral issues",
                  ["Empathy", "Communication", "Analysis"], ["Therapist", "Counselor", "Psychologist"]),
        CareerPath("Medicine", "Healthcare", "Diagnose and treat medical conditions",
                  ["Medical knowledge", "Problem-solving", "Empathy"], ["Doctor", "Physician", "Specialist"]),
        CareerPath("Pharmacy", "Healthcare", "Dispense medications and provide pharmaceutical care",
                  ["Chemistry", "Medical knowledge", "Attention to detail"], ["Pharmacist", "Pharmacy Technician", "Clinical Pharmacist"]),
        CareerPath("Physical Therapy", "Healthcare", "Help patients recover from injuries and improve mobility",
                  ["Anatomy", "Rehabilitation", "Communication"], ["Physical Therapist", "PT Assistant", "Rehabilitation Specialist"]),
        CareerPath("Dentistry", "Healthcare", "Provide dental care and oral health services",
                  ["Manual dexterity", "Medical knowledge", "Patient care"], ["Dentist", "Dental Hygienist", "Oral Surgeon"]),
        CareerPath("Medical Technology", "Healthcare", "Operate medical equipment and perform diagnostic tests",
                  ["Technical skills", "Attention to detail", "Medical knowledge"], ["Medical Technologist", "Radiologic Technician", "Lab Technician"]),
        CareerPath("Healthcare Administration", "Healthcare", "Manage healthcare facilities and operations",
                  ["Management", "Healthcare knowledge", "Administration"], ["Hospital Administrator", "Healthcare Manager", "Medical Office Manager"]),
        CareerPath("Public Health", "Healthcare", "Promote health and prevent disease in communities",
                  ["Epidemiology", "Research", "Communication"], ["Public Health Specialist", "Epidemiologist", "Health Educator"]),
        CareerPath("Veterinary Medicine", "Healthcare", "Provide medical care for animals",
                  ["Animal care", "Medical knowledge", "Empathy"], ["Veterinarian", "Vet Technician", "Animal Behaviorist"])
    ],
    "Education": [
        CareerPath("Teaching", "Education", "Educate students in various subjects and grade levels",
                  ["Communication", "Subject expertise", "Patience"], ["Teacher", "Professor", "Instructor"]),
        CareerPath("Educational Administration", "Education", "Manage educational institutions and programs",
                  ["Leadership", "Education policy", "Management"], ["Principal", "Superintendent", "Academic Dean"]),
        CareerPath("Curriculum Development", "Education", "Design and develop educational curricula and materials",
                  ["Education theory", "Subject expertise", "Writing"], ["Curriculum Designer", "Instructional Designer", "Education Consultant"]),
        CareerPath("Educational Technology", "Education", "Integrate technology into educational settings",
                  ["Technology", "Education", "Training"], ["EdTech Specialist", "Learning Technology Manager", "Digital Learning Coordinator"]),
        CareerPath("Special Education", "Education", "Provide specialized education for students with disabilities",
                  ["Patience", "Special education knowledge", "Empathy"], ["Special Education Teacher", "Learning Support Specialist", "Behavior Analyst"]),
        CareerPath("Educational Counseling", "Education", "Provide guidance and support to students",
                  ["Counseling", "Communication", "Psychology"], ["School Counselor", "Academic Advisor", "Career Counselor"]),
        CareerPath("Library Science", "Education", "Manage libraries and information resources",
                  ["Information organization", "Research", "Technology"], ["Librarian", "Information Specialist", "Digital Archivist"])
    ],
    "Social Services": [
        CareerPath("Social Work", "Social Services", "Help individuals and communities address social problems",
                  ["Empathy", "Communication", "Problem-solving"], ["Social Worker", "Case Manager", "Community Organizer"]),
        CareerPath("Counseling", "Social Services", "Provide therapeutic support and guidance",
                  ["Active listening", "Empathy", "Psychology"], ["Counselor", "Therapist", "Mental Health Specialist"]),
        CareerPath("Community Development", "Social Services", "Work to improve communities and quality of life",
                  ["Community organizing", "Grant writing", "Leadership"], ["Community Developer", "Program Director", "Nonprofit Manager"]),
        CareerPath("Criminal Justice", "Social Services", "Work within the legal system to maintain public safety",
                  ["Law knowledge", "Investigation", "Communication"], ["Police Officer", "Probation Officer", "Court Administrator"]),
        CareerPath("Public Policy", "Social Services", "Develop policies to address social issues",
                  ["Policy analysis", "Research", "Communication"], ["Policy Analyst", "Legislative Assistant", "Government Relations Specialist"]),
        CareerPath("Nonprofit Management", "Social Services", "Lead organizations focused on social causes",
                  ["Management", "Fundraising", "Mission focus"], ["Executive Director", "Program Manager", "Development Coordinator"])
    ],
    "Technology": [
        CareerPath("Cloud Computing", "Technology", "Design and manage cloud-based infrastructure and services",
                  ["Cloud platforms", "Networking", "Security"], ["Cloud Architect", "DevOps Engineer", "Cloud Consultant"]),
        CareerPath("Mobile Development", "Technology", "Create applications for mobile devices",
                  ["Mobile programming", "UI/UX", "App store optimization"], ["Mobile Developer", "iOS Developer", "Android Developer"]),
        CareerPath("Web Development", "Technology", "Build and maintain websites and web applications",
                  ["HTML/CSS", "JavaScript", "Backend development"], ["Web Developer", "Frontend Developer", "Full-Stack Developer"]),
        CareerPath("Database Administration", "Technology", "Manage and maintain database systems",
                  ["Database management", "SQL", "Security"], ["Database Administrator", "Data Engineer", "Database Architect"]),
        CareerPath("Network Administration", "Technology", "Manage computer networks and infrastructure",
                  ["Networking", "Security", "Troubleshooting"], ["Network Administrator", "Systems Administrator", "IT Manager"]),
        CareerPath("IT Support", "Technology", "Provide technical support and troubleshooting",
                  ["Problem-solving", "Communication", "Technical knowledge"], ["Help Desk Technician", "IT Support Specialist", "Technical Support Manager"])
    ],
    "Legal": [
        CareerPath("Law Practice", "Legal", "Provide legal representation and advice",
                  ["Legal knowledge", "Research", "Communication"], ["Lawyer", "Attorney", "Legal Counsel"]),
        CareerPath("Paralegal Services", "Legal", "Assist lawyers with legal research and documentation",
                  ["Legal research", "Writing", "Organization"], ["Paralegal", "Legal Assistant", "Court Reporter"]),
        CareerPath("Legal Administration", "Legal", "Manage legal offices and court systems",
                  ["Administration", "Legal knowledge", "Management"], ["Court Administrator", "Legal Office Manager", "Clerk of Court"]),
        CareerPath("Compliance", "Legal", "Ensure organizations follow laws and regulations",
                  ["Regulatory knowledge", "Risk assessment", "Analysis"], ["Compliance Officer", "Regulatory Affairs Specialist", "Ethics Officer"])
    ],
    "Media & Communications": [
        CareerPath("Public Relations", "Media & Communications", "Manage public image and communications for organizations",
                  ["Communication", "Writing", "Media relations"], ["PR Specialist", "Communications Manager", "Media Relations Director"]),
        CareerPath("Broadcasting", "Media & Communications", "Create and deliver content through radio, TV, and digital media",
                  ["Communication", "Media production", "Public speaking"], ["News Anchor", "Radio Host", "Broadcast Producer"]),
        CareerPath("Digital Marketing", "Media & Communications", "Promote brands through digital channels",
                  ["Digital marketing", "Analytics", "Content creation"], ["Digital Marketer", "Social Media Manager", "Content Strategist"]),
        CareerPath("Technical Writing", "Media & Communications", "Create technical documentation and content",
                  ["Writing", "Technical knowledge", "Communication"], ["Technical Writer", "Documentation Specialist", "Content Developer"]),
        CareerPath("Event Planning", "Media & Communications", "Organize and coordinate events and conferences",
                  ["Organization", "Project management", "Communication"], ["Event Planner", "Conference Coordinator", "Event Manager"])
    ],
    "Hospitality & Tourism": [
        CareerPath("Hotel Management", "Hospitality & Tourism", "Manage hotel operations and guest services",
                  ["Customer service", "Management", "Communication"], ["Hotel Manager", "Guest Services Manager", "Resort Director"]),
        CareerPath("Travel & Tourism", "Hospitality & Tourism", "Plan and coordinate travel experiences",
                  ["Geography", "Customer service", "Planning"], ["Travel Agent", "Tour Guide", "Tourism Manager"]),
        CareerPath("Restaurant Management", "Hospitality & Tourism", "Manage restaurant operations and staff",
                  ["Management", "Customer service", "Food service"], ["Restaurant Manager", "Food Service Director", "Catering Manager"]),
        CareerPath("Event Hospitality", "Hospitality & Tourism", "Provide hospitality services for events",
                  ["Customer service", "Event coordination", "Communication"], ["Event Coordinator", "Banquet Manager", "Convention Services Manager"])
    ],
    "Transportation & Logistics": [
        CareerPath("Aviation", "Transportation & Logistics", "Operate aircraft and manage aviation operations",
                  ["Aviation knowledge", "Safety protocols", "Decision-making"], ["Pilot", "Air Traffic Controller", "Aviation Manager"]),
        CareerPath("Maritime", "Transportation & Logistics", "Operate ships and manage maritime operations",
                  ["Navigation", "Maritime law", "Safety"], ["Ship Captain", "Marine Engineer", "Port Manager"]),
        CareerPath("Logistics Coordination", "Transportation & Logistics", "Coordinate the movement of goods and materials",
                  ["Logistics", "Planning", "Communication"], ["Logistics Coordinator", "Freight Manager", "Distribution Manager"]),
        CareerPath("Transportation Planning", "Transportation & Logistics", "Plan and design transportation systems",
                  ["Urban planning", "Engineering", "Analysis"], ["Transportation Planner", "Traffic Engineer", "Transit Manager"])
    ],
    "Agriculture & Environment": [
        CareerPath("Agriculture", "Agriculture & Environment", "Produce food and manage agricultural operations",
                  ["Agriculture knowledge", "Biology", "Management"], ["Farmer", "Agricultural Manager", "Crop Specialist"]),
        CareerPath("Environmental Conservation", "Agriculture & Environment", "Protect and preserve natural resources",
                  ["Environmental science", "Conservation", "Research"], ["Conservation Scientist", "Park Ranger", "Environmental Educator"]),
        CareerPath("Renewable Energy", "Agriculture & Environment", "Develop and manage renewable energy systems",
                  ["Engineering", "Environmental science", "Project management"], ["Renewable Energy Engineer", "Solar Installer", "Wind Technician"]),
        CareerPath("Environmental Consulting", "Agriculture & Environment", "Provide environmental expertise to organizations",
                  ["Environmental science", "Consulting", "Regulation knowledge"], ["Environmental Consultant", "Environmental Scientist", "Sustainability Consultant"])
    ],
    "Manufacturing & Trades": [
        CareerPath("Skilled Trades", "Manufacturing & Trades", "Perform specialized manual and technical work",
                  ["Manual skills", "Technical knowledge", "Problem-solving"], ["Electrician", "Plumber", "Carpenter"]),
        CareerPath("Manufacturing", "Manufacturing & Trades", "Produce goods through manufacturing processes",
                  ["Technical skills", "Quality control", "Safety"], ["Manufacturing Engineer", "Production Manager", "Quality Inspector"]),
        CareerPath("Automotive", "Manufacturing & Trades", "Design, build, and repair vehicles",
                  ["Mechanical knowledge", "Problem-solving", "Manual skills"], ["Automotive Technician", "Automotive Engineer", "Service Manager"]),
        CareerPath("Construction", "Manufacturing & Trades", "Build and renovate structures",
                  ["Construction knowledge", "Project management", "Safety"], ["Construction Manager", "Site Supervisor", "Building Inspector"])
    ]
}